```yaml
default-rank: gracz

chat:
  enabled: true
  format: "%prefix% &7%player% &8» &f%message%"

tablist:
  enabled: true
  format: "%prefix% &f%player%"

sidebar:
  enabled: true
  refresh-ticks: 20
  title: "&6&lMSURVIVAL"

  lines:
    - "&8&m━━━━━━━━━━━━━━━━"
    - "&eNick"
    - "&f%player%"
    - " "
    - "&6Ranga"
    - "%display%"
    - "&6Ważna"
    - "&e%expires%"
    - "  "
    - "&eOnline"
    - "&a%online%"
    - "   "
    - "&ePing"
    - "&b%ping% ms"
    - "    "
    - "&8&m━━━━━━━━━━━━━━━━"
    - "&6&lmsurvival.6mc.pl"

ranks:
  gracz:
    display: "&a&lGRACZ"
    prefix: "&8[&a&lGRACZ&8]"

  vip:
    display: "&b&lVIP"
    prefix: "&8[&b&lVIP&8]"

  youtuber:
    display: "&c&lYOUTUBER"
    prefix: "&8[&c▶ &f&lYT&8]"

  tiktoker:
    display: "&d&lTIKTOKER"
    prefix: "&8[&d♫ &f&lTT&8]"

  moderator:
    display: "&2&lMODERATOR"
    prefix: "&8[&2&lMOD&8]"

  zastepcaadmina:
    display: "&6&lZASTĘPCA ADMINA"
    prefix: "&8[&6&lZ-ADMIN&8]"

  admin:
    display: "&c&lADMIN"
    prefix: "&8[&c&lADMIN&8]"

  wlasciciel:
    display: "&4&lWŁAŚCICIEL"
    prefix: "&8[&4&lOWNER&8]"

messages:
  no-permission: "&cNie masz uprawnień."

  usage-setrank: "&cUżycie: &e/setrank <gracz> <ranga>"

  usage-setranktemp: "&cUżycie: &e/setranktemp <gracz> <ranga> <czas>"

  player-not-found: "&cNie znaleziono gracza."

  rank-not-found: "&cNie ma takiej rangi."

  rank-list: "&7Dostępne rangi: &e%ranks%"

  rank-set: "&aUstawiono rangę %display% &adla gracza &e%player%&a."

  temp-rank-set: "&aUstawiono rangę czasową %display% &adla &e%player% &ana &e%time%&a."

  rank-received: "&aOtrzymałeś rangę: %display%"

  temp-rank-received: "&aOtrzymałeś rangę czasową: %display% &7(&e%time%&7)"

  temp-rank-expired: "&eTwoja ranga czasowa wygasła."

  invalid-time: "&cPoprawne czasy: &e1h, 6h, 12h, 1d, 3d, 7d, 10d, 15d, 30d, 60d, 90d, 3M, 6M, 12M, 1y, 2y"

  your-rank: "&7Twoja ranga: %display%"

  reload: "&aPrzeładowano konfigurację."
```

